# ---- Build Stage ----
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Copy workspace and module files
COPY go.work go.work.sum ./
COPY api-gateway/ ./api-gateway/
COPY marketplace-app/ ./marketplace-app/
COPY shared/ ./shared/
COPY .env .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/bin/marketplace ./marketplace-app/cmd

# ---- Final Stage ----
FROM alpine:latest
WORKDIR /app
RUN adduser -D appuser
USER appuser

# Copy the compiled binary from the builder stage
COPY --from=builder /app/bin/marketplace .

# Copy the .env file from the builder stage
COPY --from=builder /app/.env .

#
# CORRECTED PATH 👇
#
# Copy the secrets directory from the builder stage
COPY --from=builder /app/shared/ ./shared/

CMD ["./marketplace"]