services:
  db:
    image: postgres:15-alpine
    container_name: marketplace_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose for local dev; remove in prod
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: marketplace_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379" # Expose for local dev; remove in prod
    networks:
      - app-network

  # api-gateway:
  #   container_name: api_gateway
  #   build:
  #     context: ./api-gateway
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}" # External:Internal port
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./api-gateway:/app
  #     - ./secrets:/app/secrets:ro # Mount key files read-only

  # Optional: Marketplace App (Uncomment if needed)
  # marketplace-app:
  #   container_name: marketplace_app
  #   build:
  #     context: ./marketplace-app
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   ports:
  #     - "${APP_PORT}:${APP_PORT}"
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./marketplace-app:/app

  # Optional: Frontend App (Uncomment when needed)
  # frontend:
  #   container_name: marketplace_frontend
  #   build:
  #     context: ./frontend-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:80"
  #   depends_on:
  #     - marketplace-app
  #   networks:
  #     - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
