name: Deploy on new commit

on:
  # 1. Trigger on commit to the main branch
  push:
    branches:
      - main

  # 2. ADDED: Allows you to trigger this manually from the "Actions" tab
  workflow_dispatch:

  # # 3. ADDED: Triggers automatically on a schedule
  # schedule:
  #   # This runs at 9:00 AM WIB every Sunday (2:00 AM UTC)
  #   - cron: '0 2 * * 0'

jobs:
  build-and-deploy:
    # This is the crucial line that tells GitHub to use your VPS
    runs-on: self-hosted

    steps:
      - name: Print starting message
        run: echo "🚀 Starting deployment..."

      # Step 1: Checks out your repository code onto your VPS runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Add your script commands here
      # This is where you tell your VPS what to do after getting the new code.
      - name: Execute Deployment Script
        run: |
          echo "✅ Code checked out. Running deployment tasks..."
          # --- ADD YOUR COMMANDS BELOW ---
          make prod-up
          echo "🎉 Deployment script finished."