name: Deploy on new commit

on:
  # 1. Trigger on commit to the main branch
  push:
    branches:
      - main

  # 2. ADDED: Allows you to trigger this manually from the "Actions" tab
  workflow_dispatch:

  # 3. ADDED: Triggers automatically on a schedule
  schedule:
    # This runs at 9:00 AM WIB every Sunday (2:00 AM UTC)
    - cron: '0 2 * * 0'

jobs:
  build-and-deploy:
    # This is the crucial line that tells GitHub to use your VPS
    runs-on: self-hosted

    steps:
      - name: Print starting message
        run: echo "🚀 Starting deployment..."

      # Step 1: Checks out your repository code onto your VPS runner
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Add your script commands here
      # This is where you tell your VPS what to do after getting the new code.
      - name: Execute Deployment Script
        env:
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          GATEWAY_PORT: ${{ secrets.GATEWAY_PORT }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_DATABASE: ${{ secrets.REDIS_DATABASE }}
          ECDSA_PRIVATE_KEY_PATH: ${{ secrets.ECDSA_PRIVATE_KEY_PATH }}
          ECDSA_PUBLIC_KEY_PATH: ${{ secrets.ECDSA_PUBLIC_KEY_PATH }}
        run: |
          echo "✅ Creating .env file..."
          echo "
          SERVER_PORT=${SERVER_PORT}
          GATEWAY_PORT=${GATEWAY_PORT}
          POSTGRES_HOST=${POSTGRES_HOST}
          POSTGRES_PORT=${POSTGRES_PORT}
          POSTGRES_USER=${POSTGRES_USER}
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          POSTGRES_DATABASE=${POSTGRES_DATABASE}
          REDIS_HOST=${REDIS_HOST}
          REDIS_PORT=${REDIS_PORT}
          REDIS_PASSWORD=${REDIS_PASSWORD}
          REDIS_DATABASE=${REDIS_DATABASE}
          ECDSA_PRIVATE_KEY_PATH=${ECDSA_PRIVATE_KEY_PATH}
          ECDSA_PUBLIC_KEY_PATH=${ECDSA_PUBLIC_KEY_PATH}
          " > .env
          echo "✅ .env file created successfully."

          echo "🔑 Generating ECDSA keys..."
          sudo ./shared/secrets/generate_ecdsa_keys.sh
          echo "✅ ECDSA keys generated successfully."

          echo "🚀 Running deployment tasks..."
          make prod-up
          echo "🎉 Deployment script finished."